### ISSUE TITLE
Add note to Readme about maximum size per imported issue is 1MB

### ISSUE THREAD

**Issue by sertel** [jeffwidman/bitbucket_issue_migration#17]
Hi,

I tried to migrate a rather large project from bitbucket to github with your script but eventually had to give up because the script kept failing with a 403 FORBIDDEN. 

I found out that the problem was not related to access rights but was due to the fact that the comments attached to some of the issues that I tried to migrate were quite big. (I always assign change sets to issues.) For these comments the according function in push_issue just failed and leaves the issue created but with only a portion of the comments added.

Maybe you can add some support for that but right now the script just can not migrate large issues which is a blocker and forced me to give up on migrating to github.

Cheers,
Sebastian

**Comment by jeffwidman** [comment]
New project maintainer here, so I'm still coming up to speed. 

Were the 403 issues from bitbucket or github? 

If the problems were github side, then #25 did a major overhaul that switched from using pygithub3 to the new Github import API--possibly this new API supports large issues, I don't know. 

Could you try it and let me know if this is still an issue?

**Comment by jeffwidman** [comment]
Actually looks like the maximum request size is 1MB according to here: https://gist.github.com/jonmagic/5282384165e0f86ef105

Using the import API gives us a bunch of niceties like avoiding rate limiting, so I don't expect to switch away from it anytime soon.

We're already doing one request per issue, rather than batching multiple issues into a single request, so we can't do any better on this unfortunately than the 1MB limit.
